### ISSUE TITLE
Convert JournalVirtualDev to use AppendBlkallocator

### ISSUE THREAD

**Issue by hkadayam** [eBay/HomeStore#147]
We will be introducing AppendBlkAllocator authored by @yamingk. Request is to use AppendBlkAllocator for JournalVirtualDev. With this some of the additional interfaces we use in VirtualDev (example: update_end_of_chunk(), all read/write API variant that pass Chunk*) shall be removed.

**Comment by sanebay** [comment]
We cant use append blk allocator due to cp. Closing this.
