### ISSUE TITLE
Implementation of basic btree/index performance benchmark

### ISSUE THREAD

**Issue by hkadayam** [eBay/HomeStore#204]
We would like to implement the basic btree/index performance benchmark using gperf. Ultimately this will be automated as a nightly job and run with test framework.

Here are the steps overall
1. Build the btree_perf_test code (reuse the existing piece of code which does something similar) using gperf library. This one is done with persistence in index and not mem-btree.
2. Run this in local machine and ensure correctness.
3. Build an image (deployable image) out of this and host them in ecr
4. Use framework to pick this nightly job and run them along with metrics page to track this.
5. This along with other performance benchmarks are sent as report in case of anomaly.

This issue is to track Item 1 and Item 2 in this list. Rest of them will be tracked with different issues later.

**Comment by JacksonYao287** [comment]
#237
