### ISSUE TITLE
New replication APIs to support blob_id generation

### ISSUE THREAD

**Issue by raakella1** [eBay/HomeStore#212]
- Extend the create pg API to accept a list of replica configs (struct with peer_id and replica_ordinal)
- Add an API to get the list replica configs of the peers

**Comment by xiaoxichen** [comment]
@raakella1 pls if you can link the PR with issue

**Comment by raakella1** [comment]
Closing this issue as it is not necessary. This issue was opened when we were planning to use an 8 bit ordinal for blob id. That design is scrapped.
