### ISSUE TITLE
CPManager abrupt shutdown method to simulate crash test

### ISSUE THREAD

**Issue by hkadayam** [eBay/HomeStore#295]
In order to do Btree repair test, we need to simulate the crash. Instead of crashing and restarting the process and validating externally, in unit test, it is better to simulate the equivalent of crash by prematurely completing the CP and doing homestore restart.

**Comment by shosseinimotlagh** [comment]
depends on `Triage crash recovery issue: sb updates while new root buffer fails` [#327](https://github.com/eBay/HomeStore/issues/327)
