### ISSUE TITLE
[BUG]  PG recovery failure caused by the postponed repl_dev recovery when restarting

### ISSUE THREAD

**Issue by JacksonYao287** [eBay/HomeStore#332]
in the current implementation , when restarting, repl_dev will not be loaded when restarting meta service, it will be postponed to the the start of raft_repl_service. but when restarting, Pg is recovered when  restarting metaservice , which will get the repl_dev from raft_repl_service, this causes an error.

**Comment by xiaoxichen** [comment]
could you link a pr to this issue

**Comment by JacksonYao287** [comment]
it is closed , this issue will be resolved in homeobject side
