### ISSUE TITLE
Flush commit_lsn on timer more frequently (outside of CP)

### ISSUE THREAD

**Issue by hkadayam** [eBay/HomeStore#422]
- Add a timer in repl service to persist durable commit LSN more frequently
- Refer to the method `start_reaper_thread` in `raft_repl_service` to add the timer
- Make sure to persist both checkpoint and durable commit LSN in a checkpoint to maintain the invariant ```Checkpoint LSN <= Durable LSN```
- On restart, reapply the logs between checkpoint commit LSN and durable commit LSN
- Use the method `register_log_found_cb` in log_store to reapply these logs
- Refer to the callback in `solo_repl_dev` for an example

**Comment by raakella1** [comment]
- Add a timer in repl service to persist durable commit LSN more frequently
- Make sure to persist both checkpoint and durable commit LSN in a checkpoint to maintain the invariant Checkpoint LSN <= Durable LSN
- On restart, reapply the logs between checkpoint commit LSN and durable commit LSN
- Use the method `register_log_found_cb` in log_store to reapply these logs
