### ISSUE TITLE
data service long run stuck at 1M ios with mixed work load

### ISSUE THREAD

**Issue by yamingk** [eBay/HomeStore#443]

**Comment by sanebay** [comment]
We have tested with SM long running and raft repl test. Please reopen if you still see the issue.

**Comment by yamingk** [comment]
Glad to know this passed the SM and raft repl test. However this issue is seen with the data service binary which is covering a different layer and test cases. If we can verify with the data service test binary itself, we can close this ticket. 

reopen it

**Comment by sanebay** [comment]
This was closed in our homestore meeting assuming its same as raft repl long running. But if data service long running has issues, lets keep it open.

**Comment by xiaoxichen** [comment]
data service long running is passing
