### ISSUE TITLE
Commit and checkpoint lsn flush.

### ISSUE THREAD

**Issue by sanebay** [eBay/HomeStore#489]
Commit and checkpoint lsn flush. From checkpoint lsn to latest, log replay should homeobject on commit, ignore any lsn from start lsn to checkpoint lsn.Any lsn between checkpoint to latest, may or might be there in btree. - Improvements.
 solution 1: - Write to disk for every commit.
 solution 2: - Batch it and commit and return to client.

**Comment by xiaoxichen** [comment]
now we flush cp_lsn after CP, and flush dc_lsn every 500ms.
for LSN between cp_lsn and dc_lsn we commit them before starting raft.
for any LSN >dc_lsn, we may or maynot commit them before restart,  but if we had committed a given LSN which measn it had reached quorum,  it will be committed by the first log from leader.
