### ISSUE TITLE
slow incremental resync speed

### ISSUE THREAD

**Issue by xiaoxichen** [eBay/HomeStore#516]
he m_resync_mode is always to false which lead each resync go through general IO path --- we queue the fetch data requests to a queue,  the reaper_thread picks from the queue and wait at least 1.5s before fetching data (https://github.com/eBay/HomeStore/blob/13a2def8befe0cc22884fc54f590fadad63d64a3/src/lib/replication/service/raft_repl_service.cpp#L386-L388),  this is the root cause of very slow resync.

**Comment by JacksonYao287** [comment]
we need to put more time one this one, right?

**Comment by xiaoxichen** [comment]
resolved
