### ISSUE TITLE
home_raft_log store should handle the start_index case when recovery from a crash

### ISSUE THREAD

**Issue by JacksonYao287** [eBay/HomeStore#530]
when we do truncation on home_raft_logstore, we only make a marker in memory and it will be persisted only when log_dev truncation is scheduled. we might lose the latest start_index of each logstore if we crash.

**Comment by xiaoxichen** [comment]
@JacksonYao287 can we close this？

**Comment by JacksonYao287** [comment]
yes , this has been fixed
