### ISSUE TITLE
OOM after follower lagging

### ISSUE THREAD

**Issue by Besroy** [eBay/HomeStore#580]
Description: During the log replay process, there is a potential issue where new data is transmitted simultaneously. This concurrent data transmission can lead to an excessive accumulation of data in memory. If the data stored in memory exceed the quota, it results in OOM.

Additional Details: For a more detailed analysis and potential mitigation strategies, please refer to the documentation available at the following link: [Google Docs](https://docs.google.com/document/d/16DMqv9J-JuNs5c25IBuX01QXe5WbxPm4B4hAfz4JNZM/edit?tab=t.0#heading=h.b4j7215dfoup)

**Comment by xiaoxichen** [comment]
@Besroy pls check if we can close this issue

**Comment by Besroy** [comment]
Test passed, close this issue
